import { useCallback, useState } from 'react'
import type { Node } from '@xyflow/react'
import type { Point, TaskPriority, TerminalNodeData } from '../../../types'
import { normalizeTaskTagSelection, toErrorMessage } from '../helpers'
import type { ContextMenuState, TaskCreatorState } from '../types'

interface UseTaskCreatorParams {
  contextMenu: ContextMenuState | null
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
  taskTagOptions: string[]
  suggestTaskTitle: (
    requirement: string,
  ) => Promise<{ title: string; priority: TaskPriority; tags: string[] }>
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
}

export function useWorkspaceCanvasTaskCreator({
  contextMenu,
  setContextMenu,
  taskTagOptions,
  suggestTaskTitle,
  createTaskNode,
}: UseTaskCreatorParams): {
  taskCreator: TaskCreatorState | null
  setTaskCreator: React.Dispatch<React.SetStateAction<TaskCreatorState | null>>
  openTaskCreator: () => void
  closeTaskCreator: () => void
  generateTaskTitle: () => Promise<void>
  createTask: () => Promise<void>
} {
  const [taskCreator, setTaskCreator] = useState<TaskCreatorState | null>(null)

  const openTaskCreator = useCallback(() => {
    if (!contextMenu || contextMenu.kind !== 'pane') {
      return
    }

    setTaskCreator({
      anchor: {
        x: contextMenu.flowX,
        y: contextMenu.flowY,
      },
      title: '',
      requirement: '',
      priority: 'medium',
      selectedTags: [],
      autoGenerateTitle: true,
      isGeneratingTitle: false,
      isCreating: false,
      error: null,
    })

    setContextMenu(null)
  }, [contextMenu, setContextMenu])

  const closeTaskCreator = useCallback(() => {
    setTaskCreator(prev => {
      if (!prev || prev.isCreating || prev.isGeneratingTitle) {
        return prev
      }

      return null
    })
  }, [])

  const generateTaskTitle = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isGeneratingTitle: true,
            error: null,
          }
        : prev,
    )

    try {
      const suggestion = await suggestTaskTitle(requirement)
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              title: suggestion.title,
              priority: suggestion.priority,
              selectedTags: suggestion.tags,
              isGeneratingTitle: false,
              error: null,
            }
          : prev,
      )
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isGeneratingTitle: false,
              error: `自动生成失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [suggestTaskTitle, taskCreator])

  const createTask = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    let title = taskCreator.title.trim()
    let priority = taskCreator.priority
    let selectedTags = normalizeTaskTagSelection(taskCreator.selectedTags, taskTagOptions)

    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isCreating: true,
            error: null,
          }
        : prev,
    )

    let autoGeneratedTitle = false

    try {
      if (title.length === 0) {
        if (!taskCreator.autoGenerateTitle) {
          setTaskCreator(prev =>
            prev
              ? {
                  ...prev,
                  isCreating: false,
                  error: '请输入任务名称或开启自动生成。',
                }
              : prev,
          )
          return
        }

        const suggestion = await suggestTaskTitle(requirement)
        title = suggestion.title
        priority = suggestion.priority
        selectedTags = suggestion.tags
        autoGeneratedTitle = true
      }

      const created = createTaskNode(
        taskCreator.anchor,
        title,
        requirement,
        autoGeneratedTitle,
        priority,
        selectedTags,
      )

      if (!created) {
        setTaskCreator(prev =>
          prev
            ? {
                ...prev,
                isCreating: false,
                error: '任务节点无法放置，请先整理画布后重试。',
              }
            : prev,
        )
        return
      }

      setTaskCreator(null)
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isCreating: false,
              error: `创建任务失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [createTaskNode, suggestTaskTitle, taskCreator, taskTagOptions])

  return {
    taskCreator,
    setTaskCreator,
    openTaskCreator,
    closeTaskCreator,
    generateTaskTitle,
    createTask,
  }
}
