import { expect, test, type Page } from '@playwright/test'
import path from 'node:path'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function readWorkspaceStateRaw(window: Page): Promise<unknown | null> {
  const raw = await window.evaluate(async () => {
    return await window.opencoveApi.persistence.readWorkspaceStateRaw()
  })

  if (!raw) {
    return null
  }

  try {
    return JSON.parse(raw) as unknown
  } catch {
    return null
  }
}

async function readTaskLinkedAgentBinding(window: Page): Promise<{
  linkedAgentNodeId: string | null
  resumeSessionId: string | null
  resumeSessionIdVerified: boolean
}> {
  const parsed = (await readWorkspaceStateRaw(window)) as {
    workspaces?: Array<{
      nodes?: Array<{
        id?: string
        kind?: string
        task?: { linkedAgentNodeId?: string | null } | null
        agent?: {
          resumeSessionId?: string | null
          resumeSessionIdVerified?: boolean
        } | null
      }>
    }>
  } | null

  const nodes = parsed?.workspaces?.[0]?.nodes ?? []
  const task = nodes.find(node => node.kind === 'task')
  const linkedAgentNodeId = task?.task?.linkedAgentNodeId ?? null
  const agent = linkedAgentNodeId
    ? nodes.find(node => node.kind === 'agent' && node.id === linkedAgentNodeId)
    : null

  return {
    linkedAgentNodeId,
    resumeSessionId: agent?.agent?.resumeSessionId ?? null,
    resumeSessionIdVerified: agent?.agent?.resumeSessionIdVerified ?? false,
  }
}

test.describe('Recovery - Agent reopen (Gemini/OpenCode)', () => {
  test('resumes a task-linked gemini agent after app restart', async () => {
    const userDataDir = await createTestUserDataDir()
    const taskDirectory = path.join(testWorkspacePath, 'docs')

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: false,
        env: {
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
          OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'gemini-user-then-gemini',
        },
      })

      let initialBinding: Awaited<ReturnType<typeof readTaskLinkedAgentBinding>>

      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'task-one',
              title: 'First task',
              position: { x: 120, y: 140 },
              width: 460,
              height: 280,
              kind: 'task',
              task: {
                requirement: 'Verify gemini resume after restart',
                status: 'todo',
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
                createdAt: '2026-03-08T00:00:00.000Z',
                updatedAt: '2026-03-08T00:00:00.000Z',
              },
            },
          ],
          {
            settings: {
              defaultProvider: 'gemini',
              customModelEnabledByProvider: {
                'claude-code': false,
                codex: false,
                opencode: false,
                gemini: true,
              },
              customModelByProvider: {
                'claude-code': '',
                codex: '',
                opencode: '',
                gemini: 'gemini-3-flash-preview',
              },
              customModelOptionsByProvider: {
                'claude-code': [],
                codex: [],
                opencode: [],
                gemini: ['gemini-3-flash-preview'],
              },
            },
            spaces: [
              {
                id: 'space-one',
                name: 'docs',
                directoryPath: taskDirectory,
                nodeIds: ['task-one'],
                rect: null,
              },
            ],
          },
        )

        await expect(window.locator('.task-node')).toHaveCount(1)
        await window.locator('.task-node [data-testid="task-node-run-agent"]').click()
        await expect(window.locator('.terminal-node')).toHaveCount(1)

        await expect
          .poll(async () => {
            const binding = await readTaskLinkedAgentBinding(window)
            return (
              typeof binding.linkedAgentNodeId === 'string' &&
              binding.linkedAgentNodeId.length > 0 &&
              binding.resumeSessionIdVerified === true &&
              typeof binding.resumeSessionId === 'string' &&
              binding.resumeSessionId.length > 0
            )
          })
          .toBe(true)

        initialBinding = await readTaskLinkedAgentBinding(window)
      } finally {
        await electronApp.close()
      }

      const { electronApp: restartedApp, window: restartedWindow } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: true,
      })

      try {
        await expect(restartedWindow.locator('.task-node')).toHaveCount(1, { timeout: 30_000 })
        await expect(restartedWindow.locator('.terminal-node')).toHaveCount(1, { timeout: 30_000 })

        const terminalNode = restartedWindow.locator('.terminal-node').first()
        await expect(terminalNode).toContainText('[opencove-test-agent] gemini resume', {
          timeout: 20_000,
        })

        await expect
          .poll(async () => {
            const binding = await readTaskLinkedAgentBinding(restartedWindow)
            return (
              binding.linkedAgentNodeId === initialBinding.linkedAgentNodeId &&
              binding.resumeSessionId === initialBinding.resumeSessionId &&
              binding.resumeSessionIdVerified === initialBinding.resumeSessionIdVerified
            )
          })
          .toBe(true)
      } finally {
        await restartedApp.close()
      }
    } finally {
      await removePathWithRetry(userDataDir)
    }
  })

  test('resumes a task-linked opencode agent after app restart', async () => {
    const userDataDir = await createTestUserDataDir()
    const taskDirectory = path.join(testWorkspacePath, 'docs')

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: false,
        env: {
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
          OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'opencode-idle-with-message',
        },
      })

      let initialBinding: Awaited<ReturnType<typeof readTaskLinkedAgentBinding>>

      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'task-one',
              title: 'First task',
              position: { x: 120, y: 140 },
              width: 460,
              height: 280,
              kind: 'task',
              task: {
                requirement: 'Verify opencode resume after restart',
                status: 'todo',
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
                createdAt: '2026-03-08T00:00:00.000Z',
                updatedAt: '2026-03-08T00:00:00.000Z',
              },
            },
          ],
          {
            settings: {
              defaultProvider: 'opencode',
              customModelEnabledByProvider: {
                'claude-code': false,
                codex: false,
                opencode: true,
                gemini: false,
              },
              customModelByProvider: {
                'claude-code': '',
                codex: '',
                opencode: 'opencode-e2e-model',
                gemini: '',
              },
              customModelOptionsByProvider: {
                'claude-code': [],
                codex: [],
                opencode: ['opencode-e2e-model'],
                gemini: [],
              },
            },
            spaces: [
              {
                id: 'space-one',
                name: 'docs',
                directoryPath: taskDirectory,
                nodeIds: ['task-one'],
                rect: null,
              },
            ],
          },
        )

        await expect(window.locator('.task-node')).toHaveCount(1)
        await window.locator('.task-node [data-testid="task-node-run-agent"]').click()
        await expect(window.locator('.terminal-node')).toHaveCount(1)

        await expect
          .poll(async () => {
            const binding = await readTaskLinkedAgentBinding(window)
            return (
              typeof binding.linkedAgentNodeId === 'string' &&
              binding.linkedAgentNodeId.length > 0 &&
              binding.resumeSessionIdVerified === true &&
              typeof binding.resumeSessionId === 'string' &&
              binding.resumeSessionId.length > 0
            )
          })
          .toBe(true)

        initialBinding = await readTaskLinkedAgentBinding(window)
      } finally {
        await electronApp.close()
      }

      const { electronApp: restartedApp, window: restartedWindow } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: true,
      })

      try {
        await expect(restartedWindow.locator('.task-node')).toHaveCount(1, { timeout: 30_000 })
        await expect(restartedWindow.locator('.terminal-node')).toHaveCount(1, { timeout: 30_000 })

        const terminalNode = restartedWindow.locator('.terminal-node').first()
        await expect(terminalNode).toContainText('[opencove-test-agent] opencode resume', {
          timeout: 20_000,
        })

        await expect
          .poll(async () => {
            const binding = await readTaskLinkedAgentBinding(restartedWindow)
            return (
              binding.linkedAgentNodeId === initialBinding.linkedAgentNodeId &&
              binding.resumeSessionId === initialBinding.resumeSessionId &&
              binding.resumeSessionIdVerified === initialBinding.resumeSessionIdVerified
            )
          })
          .toBe(true)
      } finally {
        await restartedApp.close()
      }
    } finally {
      await removePathWithRetry(userDataDir)
    }
  })
})
