import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  seedWorkspaceState,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-status-watch',
        title: 'Trace flaky status updates',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Reproduce watcher status transitions and verify standby refresh',
          status: 'todo',
          priority: 'medium',
          tags: ['debug'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-07T12:00:00.000Z',
          updatedAt: '2026-03-07T12:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: 'gpt-5.2-codex',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: ['gpt-5.2-codex'],
        },
      },
    },
  )
}

async function seedGeminiWorkspace(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(window, [], {
    settings: {
      defaultProvider: 'gemini',
      customModelEnabledByProvider: {
        'claude-code': false,
        codex: false,
        opencode: false,
        gemini: true,
      },
      customModelByProvider: {
        'claude-code': '',
        codex: '',
        opencode: '',
        gemini: 'gemini-3-flash-preview',
      },
      customModelOptionsByProvider: {
        'claude-code': [],
        codex: [],
        opencode: [],
        gemini: ['gemini-3-flash-preview'],
      },
    },
  })
}

async function seedExistingGeminiRealTurnSession(userDataDir: string): Promise<void> {
  const startedAtMs = Date.now() - 4_000
  const replyAtMs = startedAtMs + 1_200
  const geminiProjectDir = path.join(userDataDir, 'home', '.gemini', 'tmp', 'existing-session')
  const chatsDir = path.join(geminiProjectDir, 'chats')

  await mkdir(chatsDir, { recursive: true })
  await writeFile(path.join(geminiProjectDir, '.project_root'), testWorkspacePath, 'utf8')
  await writeFile(
    path.join(chatsDir, 'session-existing.json'),
    JSON.stringify(
      {
        sessionId: 'existing-real-turn-session',
        projectHash: 'existing-project-hash',
        startTime: new Date(startedAtMs).toISOString(),
        lastUpdated: new Date(replyAtMs).toISOString(),
        kind: 'main',
        messages: [
          {
            id: `user-${startedAtMs}`,
            timestamp: new Date(startedAtMs).toISOString(),
            type: 'user',
            content: [{ text: 'old prompt' }],
          },
          {
            id: `gemini-${replyAtMs}`,
            timestamp: new Date(replyAtMs).toISOString(),
            type: 'gemini',
            content: 'old reply',
          },
        ],
      },
      null,
      2,
    ),
    'utf8',
  )
}

async function seedCodexTaskInMultipleWorkspaces(
  window: Awaited<ReturnType<typeof launchApp>>['window'],
) {
  await seedWorkspaceState(window, {
    activeWorkspaceId: 'workspace-a',
    workspaces: [
      {
        id: 'workspace-a',
        name: 'workspace-a',
        path: testWorkspacePath,
        nodes: [
          {
            id: 'task-status-watch',
            title: 'Trace flaky status updates',
            position: { x: 180, y: 140 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'Reproduce watcher status transitions and verify standby refresh',
              status: 'todo',
              priority: 'medium',
              tags: ['debug'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-03-07T12:00:00.000Z',
              updatedAt: '2026-03-07T12:00:00.000Z',
            },
          },
        ],
      },
      {
        id: 'workspace-b',
        name: 'workspace-b',
        path: `${testWorkspacePath}-b`,
        nodes: [],
      },
    ],
    settings: {
      defaultProvider: 'codex',
      customModelEnabledByProvider: {
        'claude-code': false,
        codex: true,
      },
      customModelByProvider: {
        'claude-code': '',
        codex: 'gpt-5.2-codex',
      },
      customModelOptionsByProvider: {
        'claude-code': [],
        codex: ['gpt-5.2-codex'],
      },
    },
  })
}

test.describe('Workspace Canvas - Agent Status Watcher', () => {
  test('keeps gemini in standby while typing and only switches to working after submit', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'gemini-stdin-submit-then-reply',
      },
    })

    try {
      await seedGeminiWorkspace(window)

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 320, y: 220 },
      })

      const runButton = window.locator('[data-testid="workspace-context-run-default-agent"]')
      await expect(runButton).toBeVisible()
      await runButton.click()

      const agentNode = window.locator('.terminal-node').first()
      const xterm = agentNode.locator('.xterm')
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()

      await expect(agentNode).toBeVisible()
      await expect(xterm).toBeVisible()
      await expect(agentNode).toContainText('[cove-test-agent] gemini new')
      await expect(nodeStatus).toHaveText('Standby')
      await expect(sidebarStatus).toHaveText('Standby')

      await xterm.click()
      await window.keyboard.type('Return OK only.')
      await window.waitForTimeout(900)

      await expect(nodeStatus).toHaveText('Standby')
      await expect(sidebarStatus).toHaveText('Standby')

      await window.keyboard.press('Enter')

      await expect(nodeStatus).toHaveText('Working', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Working')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })

  test('binds a new gemini launch even when an older real-turn session already exists', async () => {
    const userDataDir = await createTestUserDataDir()
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      userDataDir,
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'gemini-stdin-submit-then-reply',
      },
    })

    try {
      await seedExistingGeminiRealTurnSession(userDataDir)
      await seedGeminiWorkspace(window)

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 320, y: 220 },
      })

      const runButton = window.locator('[data-testid="workspace-context-run-default-agent"]')
      await expect(runButton).toBeVisible()
      await runButton.click()

      const agentNode = window.locator('.terminal-node').first()
      const xterm = agentNode.locator('.xterm')
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()

      await expect(agentNode).toBeVisible()
      await expect(agentNode).toContainText('[cove-test-agent] gemini new')
      await expect(nodeStatus).toHaveText('Standby')
      await expect(sidebarStatus).toHaveText('Standby')

      await xterm.click()
      await window.keyboard.type('Return OK only.')
      await window.keyboard.press('Enter')

      await expect(nodeStatus).toHaveText('Working', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Working')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })

  test('updates an active agent from working to standby when the last session line has no newline', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTask(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()
      const taskStatus = taskNode.locator('[data-testid="task-node-status-select"]')

      await expect(agentNode).toBeVisible()
      await expect(taskStatus).toHaveValue('doing')
      await expect(agentNode).toContainText('[cove-test-agent] codex new')
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })

  test('keeps updating a non-focused project agent status after switching projects', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTaskInMultipleWorkspaces(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      await expect(agentNode).toBeVisible()

      const workspaceAGroup = window
        .locator('.workspace-item-group')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-a' }) })

      const workspaceAStatus = workspaceAGroup
        .locator('.workspace-agent-item__status--agent')
        .first()

      await expect(workspaceAStatus).toHaveText('Working')

      await window.locator('.workspace-item__name', { hasText: 'workspace-b' }).click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-b',
      )

      await expect(workspaceAStatus).toHaveText('Standby', { timeout: 15_000 })
    } finally {
      await electronApp.close()
    }
  })

  test('keeps codex in working during commentary until the final answer arrives', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-commentary-then-final',
      },
    })

    try {
      await seedCodexTask(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()

      await expect(agentNode).toBeVisible()
      await expect(agentNode).toContainText('[cove-test-agent] codex new')
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await window.waitForTimeout(2600)
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await window.waitForTimeout(1400)
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })
})
