import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Tasks (Create & Assign)', () => {
  test('creates task node with auto title and runs linked agent', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [], {
        settings: {
          defaultProvider: 'codex',
          customModelEnabledByProvider: {
            'claude-code': false,
            codex: true,
          },
          customModelByProvider: {
            'claude-code': '',
            codex: 'gpt-5.2-codex',
          },
          customModelOptionsByProvider: {
            'claude-code': [],
            codex: ['gpt-5.2-codex'],
          },
          taskTitleProvider: 'codex',
          taskTitleModel: 'gpt-5.2-codex',
          taskTagOptions: ['auth', 'retry'],
        },
      })

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 320, y: 220 },
      })

      await window.locator('[data-testid="workspace-context-new-task"]').click()

      const taskCreator = window.locator('[data-testid="workspace-task-creator"]')
      await expect(taskCreator).toBeVisible()

      const requirement = window.locator('[data-testid="workspace-task-requirement"]')
      await requirement.fill('Implement login retry with exponential backoff and jitter')

      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await expect(taskNode.locator('.task-node__title')).toContainText('Auto:')
      await expect(taskNode.locator('.task-node__priority')).toHaveText('MEDIUM')
      await expect(taskNode.locator('[data-testid="task-node-tags"]')).toContainText('#auth')

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(window.locator('.workspace-agent-item')).toHaveCount(1)

      const taskStatus = taskNode.locator('[data-testid="task-node-status-select"]')
      await expect(taskStatus).toHaveValue('doing')

      const persisted = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              kind?: string
              title?: string
              task?: {
                requirement?: string
                priority?: string
                tags?: string[]
                autoGeneratedTitle?: boolean
              }
            }>
          }>
        }

        return parsed.workspaces?.[0]?.nodes?.find(node => node.kind === 'task') ?? null
      }, storageKey)

      expect(persisted).toBeTruthy()
      expect(persisted?.task?.requirement).toContain('exponential backoff')
      expect(persisted?.task?.priority).toBe('medium')
      expect(persisted?.task?.tags).toEqual(['auth'])
      expect(persisted?.task?.autoGeneratedTitle).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('supports manual task assignment and renders task-agent cable', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-assign-1',
          title: 'Prepare release notes',
          position: { x: 180, y: 140 },
          width: 460,
          height: 280,
          kind: 'task',
          status: null,
          task: {
            requirement: 'Summarize user-facing changes for this release',
            status: 'todo',
            priority: 'medium',
            tags: ['release'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-12T09:30:00.000Z',
            updatedAt: '2026-02-12T09:30:00.000Z',
          },
        },
        {
          id: 'agent-assign-1',
          title: 'codex · gpt-5.2-codex',
          position: { x: 760, y: 180 },
          width: 520,
          height: 360,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-12T09:40:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: '[cove-test-agent] ready',
          agent: {
            provider: 'codex',
            prompt: 'Summarize release notes',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'new',
            resumeSessionId: null,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-assign-agent"]').click()

      const assigner = window.locator('[data-testid="workspace-task-assigner"]')
      await expect(assigner).toBeVisible()

      await window
        .locator('[data-testid="workspace-task-assign-select"]')
        .selectOption('agent-assign-1')
      await window.locator('[data-testid="workspace-task-assign-submit"]').click()

      await expect(assigner).toHaveCount(0)
      await expect(taskNode.locator('[data-testid="task-node-linked-agent"]')).toContainText(
        'codex · gpt-5.2-codex',
      )
      await expect(window.locator('.workspace-task-agent-edge')).toHaveCount(1)

      const persisted = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id?: string
              task?: {
                linkedAgentNodeId?: string | null
              }
              agent?: {
                taskId?: string | null
              }
            }>
          }>
        }

        const nodes = parsed.workspaces?.[0]?.nodes ?? []
        const taskNode = nodes.find(node => node.id === 'task-assign-1')
        const agentNode = nodes.find(node => node.id === 'agent-assign-1')

        return {
          taskLinkedAgentNodeId: taskNode?.task?.linkedAgentNodeId ?? null,
          agentTaskId: agentNode?.agent?.taskId ?? null,
        }
      }, storageKey)

      expect(persisted).toEqual({
        taskLinkedAgentNodeId: 'agent-assign-1',
        agentTaskId: 'task-assign-1',
      })
    } finally {
      await electronApp.close()
    }
  })
})
