export const STORAGE_KEY = 'cove:m0:workspace-state'
export const DEFAULT_PERSIST_WRITE_DEBOUNCE_MS = 800
export const MAX_PERSISTED_SCROLLBACK_CHARS = 400_000
export const PERSISTED_APP_STATE_FORMAT_VERSION = 1
