import type {
  AgentNodeData,
  PersistedTerminalNode,
  PersistedWorkspaceState,
  TaskNodeData,
} from '../../types'
import type { WorkspaceSpaceState } from '../../types'
import {
  normalizeAgentRuntimeStatus,
  normalizeDirectoryMode,
  normalizeLaunchMode,
  normalizeNodeKind,
  normalizeOptionalString,
  normalizeProvider,
  normalizeScrollback,
  normalizeTaskPriority,
  normalizeTaskRuntimeStatus,
  normalizeTaskTags,
  normalizeWorkspaceMinimapVisible,
  normalizeWorkspaceSpaceNodeIds,
  normalizeWorkspaceSpaceRect,
  normalizeWorkspaceViewport,
} from './normalize'

function ensurePersistedWorkspaceSpace(
  value: unknown,
  workspacePath: string,
): WorkspaceSpaceState | null {
  if (!value || typeof value !== 'object') {
    return null
  }

  const record = value as Record<string, unknown>
  const id = record.id
  const name = record.name

  if (typeof id !== 'string' || typeof name !== 'string') {
    return null
  }

  const normalizedDirectoryPath = normalizeOptionalString(record.directoryPath) ?? workspacePath

  return {
    id,
    name,
    directoryPath: normalizedDirectoryPath,
    nodeIds: normalizeWorkspaceSpaceNodeIds(record.nodeIds),
    rect: normalizeWorkspaceSpaceRect(record.rect),
  }
}

function ensurePersistedAgentData(value: unknown): AgentNodeData | null {
  if (!value || typeof value !== 'object') {
    return null
  }

  const record = value as Record<string, unknown>
  const provider = normalizeProvider(record.provider)
  const prompt = normalizeOptionalString(record.prompt)
  const executionDirectory = normalizeOptionalString(record.executionDirectory)

  if (!provider || !prompt || !executionDirectory) {
    return null
  }

  return {
    provider,
    prompt,
    model: normalizeOptionalString(record.model),
    effectiveModel: normalizeOptionalString(record.effectiveModel),
    launchMode: normalizeLaunchMode(record.launchMode),
    resumeSessionId: normalizeOptionalString(record.resumeSessionId),
    executionDirectory,
    directoryMode: normalizeDirectoryMode(record.directoryMode),
    customDirectory: normalizeOptionalString(record.customDirectory),
    shouldCreateDirectory:
      typeof record.shouldCreateDirectory === 'boolean' ? record.shouldCreateDirectory : false,
    taskId: normalizeOptionalString(record.taskId),
  }
}

function ensurePersistedTaskData(value: unknown): TaskNodeData | null {
  if (!value || typeof value !== 'object') {
    return null
  }

  const record = value as Record<string, unknown>
  const requirement = normalizeOptionalString(record.requirement)

  if (!requirement) {
    return null
  }

  return {
    requirement,
    status: normalizeTaskRuntimeStatus(record.status),
    priority: normalizeTaskPriority(record.priority),
    tags: normalizeTaskTags(record.tags),
    linkedAgentNodeId: normalizeOptionalString(record.linkedAgentNodeId),
    lastRunAt: normalizeOptionalString(record.lastRunAt),
    autoGeneratedTitle:
      typeof record.autoGeneratedTitle === 'boolean' ? record.autoGeneratedTitle : false,
    createdAt: normalizeOptionalString(record.createdAt),
    updatedAt: normalizeOptionalString(record.updatedAt),
  }
}

function ensurePersistedNode(node: unknown): PersistedTerminalNode | null {
  if (!node || typeof node !== 'object') {
    return null
  }

  const record = node as Record<string, unknown>
  const id = record.id
  const title = record.title
  const width = record.width
  const height = record.height
  const position = record.position

  if (
    typeof id !== 'string' ||
    typeof title !== 'string' ||
    typeof width !== 'number' ||
    typeof height !== 'number' ||
    !position ||
    typeof position !== 'object'
  ) {
    return null
  }

  const positionRecord = position as Record<string, unknown>
  if (typeof positionRecord.x !== 'number' || typeof positionRecord.y !== 'number') {
    return null
  }

  const kind = normalizeNodeKind(record.kind)
  const agent = ensurePersistedAgentData(record.agent)
  const task = ensurePersistedTaskData(record.task)

  return {
    id,
    title,
    width,
    height,
    kind,
    status: normalizeAgentRuntimeStatus(record.status),
    startedAt: normalizeOptionalString(record.startedAt),
    endedAt: normalizeOptionalString(record.endedAt),
    exitCode: typeof record.exitCode === 'number' ? record.exitCode : null,
    lastError: normalizeOptionalString(record.lastError),
    scrollback: normalizeScrollback(record.scrollback),
    agent: kind === 'agent' ? agent : null,
    task: kind === 'task' ? task : null,
    position: {
      x: positionRecord.x,
      y: positionRecord.y,
    },
  }
}

export function ensurePersistedWorkspace(workspace: unknown): PersistedWorkspaceState | null {
  if (!workspace || typeof workspace !== 'object') {
    return null
  }

  const record = workspace as Record<string, unknown>
  const id = record.id
  const name = record.name
  const path = record.path
  const nodes = record.nodes
  const spaces = record.spaces
  const activeSpaceId = record.activeSpaceId

  if (typeof id !== 'string' || typeof name !== 'string' || typeof path !== 'string') {
    return null
  }

  if (!Array.isArray(nodes)) {
    return null
  }

  const normalizedNodes = nodes
    .map(node => ensurePersistedNode(node))
    .filter((node): node is PersistedTerminalNode => node !== null)

  const normalizedSpaces = Array.isArray(spaces)
    ? spaces
        .map(item => ensurePersistedWorkspaceSpace(item, path))
        .filter((item): item is WorkspaceSpaceState => item !== null)
    : []

  const availableNodeIds = new Set(normalizedNodes.map(node => node.id))
  const sanitizedSpaces = normalizedSpaces.map(space => ({
    ...space,
    nodeIds: space.nodeIds.filter(nodeId => availableNodeIds.has(nodeId)),
  }))
  const normalizedActiveSpaceId = typeof activeSpaceId === 'string' ? activeSpaceId : null
  const resolvedActiveSpaceId =
    normalizedActiveSpaceId && sanitizedSpaces.some(space => space.id === normalizedActiveSpaceId)
      ? normalizedActiveSpaceId
      : null

  return {
    id,
    name,
    path,
    nodes: normalizedNodes,
    viewport: normalizeWorkspaceViewport(record.viewport),
    isMinimapVisible: normalizeWorkspaceMinimapVisible(record.isMinimapVisible),
    spaces: sanitizedSpaces,
    activeSpaceId: resolvedActiveSpaceId,
  }
}
