import type { Node } from '@xyflow/react'
import type {
  NoteNodeData,
  PersistedWorkspaceState,
  TaskNodeData,
  TerminalNodeData,
} from '../types'

function isTaskNodeData(value: TaskNodeData | NoteNodeData | null): value is TaskNodeData {
  return value !== null && typeof value === 'object' && 'requirement' in value
}

function isNoteNodeData(value: TaskNodeData | NoteNodeData | null): value is NoteNodeData {
  return value !== null && typeof value === 'object' && 'text' in value
}

export function toRuntimeNodes(workspace: PersistedWorkspaceState): Node<TerminalNodeData>[] {
  return workspace.nodes.map(node => {
    const defaultTask: TaskNodeData = {
      requirement: '',
      status: 'todo',
      priority: 'medium',
      tags: [],
      linkedAgentNodeId: null,
      agentSessions: [],
      lastRunAt: null,
      autoGeneratedTitle: false,
      createdAt: null,
      updatedAt: null,
    }
    const task: TaskNodeData | null =
      node.kind === 'task' ? (isTaskNodeData(node.task) ? node.task : defaultTask) : null
    const note =
      node.kind === 'note' ? (isNoteNodeData(node.task) ? node.task : { text: '' }) : null

    const runtimeNode: Node<TerminalNodeData> = {
      id: node.id,
      type: node.kind === 'task' ? 'taskNode' : node.kind === 'note' ? 'noteNode' : 'terminalNode',
      position: node.position,
      data: {
        sessionId: '',
        profileId: node.profileId,
        runtimeKind: node.runtimeKind,
        labelColorOverride: node.labelColorOverride ?? null,
        title: node.title,
        titlePinnedByUser: node.titlePinnedByUser === true,
        width: node.width,
        height: node.height,
        kind: node.kind,
        status: node.status,
        startedAt: node.startedAt,
        endedAt: node.endedAt,
        exitCode: node.exitCode,
        lastError: node.lastError,
        scrollback: node.scrollback,
        executionDirectory: node.executionDirectory,
        expectedDirectory: node.expectedDirectory,
        agent: node.agent,
        task,
        note,
      },
      draggable: true,
      selectable: node.kind !== 'note',
    }

    return runtimeNode
  })
}
